### PR TITLE
Rename roles / variables from pandoc to converter

### PR DESCRIPTION
**Pull request by yakky**
Remove explicit references to pandoc in role name, variables etc, use converter instead

### CODE REVIEW

**Comment by danse** [comment]
rather than _converter_ i would call these the _commands_, to tell them apart from the web converter software

**Comment by danse** [comment]
cool :+1: 

usually we shorten these as the _commands_ but it's really generic. maybe _conversion commands_. anyway feel free to name it as you like it better :)

**Comment by yakky** [comment]
@danse in the context of the docs.italia platformm commands it's too generic. After all the roles are finalized to install the web converter rather than "standalone" commands / filters
@xrmx @francescozaia what's your opinion on the naming (which is rather minimal, I convene)

**Comment by francescozaia** [comment]
I agree on the `converter` naming.
I don't get @danse point: when you say _"i would call these the commands, to tell them apart from the web converter software"_. This **is** the web converter software... or am I missing something - which is very likely? 😄

**Comment by yakky** [comment]
Probably @danse though we could make this role reusable outside of the docs.italia platform, but I think it's stretching this too much, at least for now. As discussed in italia/docs-italia-comandi-conversione#35 releasing a docker container it's the easies way to distribute commands / filters for standalone use

**Comment by yakky** [comment]
Merging this. @danse feel free to submit further comments when you'll be back

**Pull request merged**
