### PR TITLE
Add roles to setup converter

### PR DESCRIPTION
**Pull request by yakky**
This adds a new role to setup the converter commands and pandoc filter
and it installs and configure the web converter
https://github.com/italia/docs-italia-convertitore-web

This needs https://github.com/italia/docs.italia.it/pull/45

### CODE REVIEW

**Comment by danse** [comment]
> it would be very nice to get haskell / pandoc already built inside a docker image instead of building on the deploy machine

it would be more efficient but less flexible

**Comment by danse** [comment]
If there would be a way to manage the executables without the need to enumerate them, it would make maintenance easier. Especially in the case of the commands starting with `filter-`, that change more frequently.

**Comment by xrmx** [comment]
@danse would it be technically feasible to just do a single binary with different commands? Or maybe you'll create a makefile and we'll execute make install

**Comment by danse** [comment]
i would exclude doing a single binary. I have no problems with maintaining a makefile!

**Pull request merged**
